require("screensaver").setup({
  idle_ms = 20 * 1000,
  auto_start = true,
  disable_on_focus_lost = true,
  exit_key = "<Esc>",
  custom_commands = {
    aquarium = "asciiquarium -t",
    -- cmatrix = "cmatrix -s",
    -- nyancat = "nyancat",
    -- train = "while true; do sl -aF; done",
    -- figlet = "watch -n 1 'echo Neovim | figlet | lolcat'",
  },
  animations = {
    -- "rain",
    "aquarium",
    -- "train",
    -- "move_left",
    -- "move_right",
    -- "scramble",
    -- "random_case",
    -- "cmatrix",
    -- "nyancat",
    -- "figlet",
    -- "matrix",
    -- "game_of_life",
    -- "bounce",
    -- "starfield",
    -- "pipes",
    -- "fire",
    -- "snow",
    -- "zoo",
  },
  -- Window transparency (0-100)
  winblend = 65,
})
